name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
      options: --user root # to run as root user
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          apk update
          apk add hugo git 
          git clone https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          hugo