name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "hugomods/hugo"
      options: --user root # to run as root user
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: hugo